return {
	-- useful plugin to show you pending keybinds
	"folke/which-key.nvim",
	event = "VimEnter", -- Sets the loading event to 'VimEnter'
	opts = {
		-- delay between pressing a key and opening which-key (milliseconds)
		-- this setting is independent of vim.opt.timeoutlen
		delay = 300,
		presets = {
			operators = false,
			motions = false,
			text_objects = false,
			windows = true,
		},
		plugins = {
			marks = false,
			registers = false,
			spelling = {
				enabled = false,
			},
		},
		layout = {
			height = { min = 30, max = 250 },
		},
		win = {
			padding = { 2, 2 },
		},

		icons = {
			-- set icon mappings to true if you have a Nerd Font
			mappings = vim.g.have_nerd_font,
			-- If you are using a Nerd Font: set icons.keys to an empty table which will use the
			-- default which-key.nvim defined Nerd Font icons, otherwise define a string table
			keys = vim.g.have_nerd_font and {} or {
				Up = "<Up> ",
				Down = "<Down> ",
				Left = "<Left> ",
				Right = "<Right> ",
				C = "<C-…> ",
				M = "<M-…> ",
				D = "<D-…> ",
				S = "<S-…> ",
				CR = "<CR> ",
				Esc = "<Esc> ",
				ScrollWheelDown = "<ScrollWheelDown> ",
				ScrollWheelUp = "<ScrollWheelUp> ",
				NL = "<NL> ",
				BS = "<BS> ",
				Space = "<Space> ",
				Tab = "<Tab> ",
				F1 = "<F1>",
				F2 = "<F2>",
				F3 = "<F3>",
				F4 = "<F4>",
				F5 = "<F5>",
				F6 = "<F6>",
				F7 = "<F7>",
				F8 = "<F8>",
				F9 = "<F9>",
				F10 = "<F10>",
				F11 = "<F11>",
				F12 = "<F12>",
			},
		},
		spec = {
			{ "<leader><leader>", "<Cmd>BufferLinePick<cr>", desc = "Pick Buffer" },
			{ "<leader>a", group = "Gp" },
			{ "<leader>ai", "<Cmd>GpRewrite<cr>", desc = "Rewrite code" },
			{ "<leader>aa", "<Cmd>GpAppend<cr>", desc = "Append code" },
			{ "<leader>ap", "<Cmd>GpPrepend<cr>", group = "Prepend code" },
			{ "<leader>ac", "<Cmd>GpNew<cr>", desc = "Open prompt" },
			{ "<leader>b", group = "Bufferline" },
			{ "<leader>bc", "<Cmd>bd<cr>", desc = "Close buffer" },
			{ "<leader>bl", "<Cmd>BufferLineCloseLeft<CR>", desc = "Delete buffers to the left" },
			{ "<leader>bn", "<Cmd>BufferLineGroupClose ungrouped<CR>", desc = "Delete non-pinned buffers" },
			{ "<leader>bo", "<Cmd>BufferLineCloseOthers<CR>", desc = "Close Other Buffers" },
			{ "<leader>bp", "<Cmd>BufferLineTogglePin<cr>", desc = "Toggle Pin" },
			{ "<leader>br", "<Cmd>BufferLineCloseRight<CR>", desc = "Delete buffers to the right" },
			{ "<leader>e", group = "Errors" },
			{ "<leader>ee", "<cmd>lua vim.diagnostic.open_float()<CR>", desc = "Show Diagnostic For Error" },
			{ "<leader>ej", "<cmd>lua vim.diagnostic.goto_next()<CR>", desc = "Next Diagnostic" },
			{ "<leader>ek", "<cmd>lua vim.diagnostic.goto_prev()<CR>", desc = "Prev Diagnostic" },
			{ "<leader>g", group = "Git" },
			{ "<leader>gb", "<cmd>Gitsigns blame_line<CR>", desc = "Blame line" },
			{ "<leader>gd", "<cmd>Gitsigns preview_hunk<CR>", desc = "Diff" },
			{ "<leader>gh", "<cmd>Gitsigns toggle_linehl<cr>", desc = "Toggle line highlights" },
			{ "<leader>gj", "<cmd>Gitsigns next_hunk<cr>", desc = "Next hunk" },
			{ "<leader>gk", "<cmd>Gitsigns prev_hunk<cr>", desc = "Prev hunk" },
			{ "<leader>gq", "<cmd>Gitsigns reset_buffer<cr>", desc = "Reset current buffer" },
			{ "<leader>gr", "<cmd>Gitsigns reset_hunk<cr>", desc = "Reset hunk" },
			{ "<leader>gs", "<cmd>Gitsigns stage_hunk<cr>", desc = "Stage hunk" },
			{ "<leader>gu", "<cmd>Gitsigns undo_stage_hunk<cr>", desc = "Undo stage hunk" },
			{ "<leader>gv", "<cmd>Gitsigns toggle_current_line_blame<cr>", desc = "Toggle current line blame" },
			{ "<leader>gw", "<cmd>Gitsigns toggle_word_diff<cr>", desc = "Toggle word diff" },
			{ "<leader>n", group = "Noice" },
			{ "<leader>nd", "<cmd>Noice dismiss<CR>", desc = "Dismiss Notifications" },
			{ "<leader>nl", "<cmd>Noice last<CR>", desc = "Noice Last Message" },
			{ "<leader>o", group = "Oil" },
			{ "<leader>oo", "<cmd>Oil<cr>", desc = "Open Oil" },
			{ "<leader>t", group = "Telescope" },
			{
				"<leader>tc",
				"<cmd>lua require('telescope.builtin').current_buffer_fuzzy_find({ layout_strategy = 'horizontal' })<cr>",
				desc = "Fuzzy Search Current Buffer",
			},
			{
				"<leader>td",
				"<cmd>lua require('telescope.builtin').lsp_definitions()<cr>",
				desc = "Go to or show definiton",
			},
			{
				"<leader>te",
				"<cmd>lua require('telescope.builtin').diagnostics({ initial_mode = 'normal', path_display='hidden', wrap_results = true })<cr>",
				desc = "List Errors For Buffers",
			},
			{
				"<leader>tf",
				"<cmd>lua require('telescope.builtin').find_files()<cr>",
				desc = "Find files in current directory",
			},
			{ "<leader>tg", "<cmd>lua require('telescope.builtin').git_status()<cr>", desc = "Show git files" },
			{ "<leader>th", "<cmd>lua require('telescope.builtin').search_history()<cr>", desc = "Search History" },
			{
				"<leader>tj",
				"<cmd>Telescope jsonfly<cr>",
				desc = "Open json(fly)",
				mode = "n",
			},
			{ "<leader>tm", "<cmd>lua require('telescope.builtin').marks()<cr>", desc = "Marks" },
			{ "<leader>tn", "<cmd>Telescope noice<cr>", desc = "Show Notification History" },
			{ "<leader>to", "<cmd>lua require('telescope.builtin').oldfiles()<cr>", desc = "Recent Files" },
			{
				"<leader>tq",
				"<cmd>lua require('telescope.builtin').quickfix()<cr>",
				desc = "List items in quickfix",
			},
			{ "<leader>tr", "<cmd>Telescope registers<cr>", desc = "Registers" },
			{ "<leader>ts", "<cmd>lua require('telescope.builtin').live_grep()<cr>", desc = "Grep Cursor Word" },
			{ "<leader>tt", "<cmd>Telescope git_files<cr>", desc = "Gitfiles (working directory)" },
			{ "<leader>tx", "<cmd>lua require('telescope.builtin').grep_string()<cr>", desc = "Grep Cursor Word" },
		},
	},
}
